"""
Field definitions for the Lebanese driving license (front + back), and the
mapping from Lebanese license categories to the IDP's A/B/C/D/E categories.

The license itself is a standardized layout (same numbered fields printed
on every one), so rather than free-form OCR + guessing, the OCR step should
crop known regions relative to the detected card corners and read each
region individually. This file documents where each numbered field is and
what it means, based on the printed field key on the back of the card.
"""

# Front of card: numbered fields as printed (field number -> meaning)
LICENSE_FRONT_FIELDS = {
    "1": "surname",              # Family name
    "2": "given_name",           # First/given name
    "3": "dob_and_place_of_birth",  # printed together: DOB then place of birth line below
    "4a": "issue_date",
    "4b": "expiry_date",
    "4c": "issuing_authority",
    "5": "license_number",
    "7": "holder_signature",
    "8": "place_of_residence",
    "9": "vehicle_categories_placeholder",  # actual category grid is on the back
    "13a": "nationality",
    "13b": "blood_type",
    "13c": "father_name",
    "13d": "mother_name",
    "15": "sex",
}

# Back of card: category table + serial numbers
LICENSE_BACK_FIELDS = {
    "5_repeated": "license_number",       # printed vertically on the back too
    "SAI": "administrative_code",
    "9": "category_table",   # rows: A1, A, B1, B, C1, C, CE, D1, D, agricultural, equipment
    "10": "date_of_issue_per_category",
    "11": "date_of_expiry_per_category",
    "12": "restrictions",
}

LICENSE_CATEGORIES = [
    "A1", "A", "B1", "B", "C1", "C", "CE", "D1", "D",
    "agricultural_vehicles", "construction_equipment",
]

# International Driving Permit (1949 Geneva Convention) only has 5 broad
# categories on its data page. This maps a Lebanese license category to the
# IDP category it authorizes, based on the vehicle descriptions printed on
# the IDP's own legend pages (motorcycles / cars / trucks / buses / trailers).
LEBANESE_TO_IDP_CATEGORY = {
    "A1": "A",   # light motorcycle -> IDP A (motorcycles)
    "A":  "A",   # motorcycle -> IDP A
    "B1": "B",   # light car -> IDP B (cars, up to 3500kg / 8 passengers)
    "B":  "B",   # car -> IDP B
    "C1": "C",   # medium truck -> IDP C (goods vehicles over 3500kg)
    "C":  "C",   # truck -> IDP C
    "CE": "C",   # truck + trailer -> IDP C (E noted as restriction, not separate box)
    "D1": "D",   # minibus -> IDP D (more than 8 passengers)
    "D":  "D",   # bus -> IDP D
    # Agricultural vehicles / construction equipment have no direct IDP
    # equivalent and are typically not carried over onto the permit.
    "agricultural_vehicles": None,
    "construction_equipment": None,
}


def categories_to_idp(held_categories: list[str]) -> set[str]:
    """Given a list of Lebanese categories the holder is licensed for
    (i.e. rows on the back of the card that have a date filled in, not
    blank), return the set of IDP boxes (A-E) that should be checked/stamped."""
    idp_boxes = set()
    for cat in held_categories:
        mapped = LEBANESE_TO_IDP_CATEGORY.get(cat)
        if mapped:
            idp_boxes.add(mapped)
    return idp_boxes


# ---------------------------------------------------------------------------
# Mapping from extracted ID data -> the "New IDL" app form fields, matching
# the LAA screen field-for-field so the same OCR output can drive our own
# equivalent form.
# ---------------------------------------------------------------------------
APP_FORM_FIELD_SOURCES = {
    "Surname":            "passport.surname (MRZ)  (fallback: license.surname)",
    "First Name":         "passport.given_names (MRZ)  (fallback: license.given_name)",
    "Father's Name":      "passport.father_name (bio-data page)  (fallback: license.father_name)",
    "Mother's Name":      "passport.mother_full_name  (not currently extracted - no bio-data-page region yet)",
    "Place of B.":        "passport.place_of_birth (bio-data page)  (fallback: license.dob_and_place_of_birth)",
    "Date of B.":         "passport.date_of_birth (MRZ)  (fallback: license.dob_and_place_of_birth)",
    "Address":            "license.place_of_residence",
    "Phone":              None,   # not on any ID document - manual entry
    "Email":              None,   # not on any ID document - manual entry
    "Blood Type":         "license.blood_type",
    "Original Document.Number":     "license.license_number",
    "Original Document.Date":       "license.issue_date",
    "Original Document.PlaceOfIssue": "license.issuing_authority",
    "Original Document.Category":   "license.category_table -> categories_to_idp()",
    "Original Document.ExpiryDate": "license.expiry_date",
    "Issued Document.Number":   None,  # generated by the app (next sequence number)
    "Issued Document.Date":     "today's date",
    "Issued Document.Signature": None,  # manual, physically signed
}


if __name__ == "__main__":
    # Sanity test using the sample license (Georges El Alam) - held categories
    # are inferred from which rows have a date filled in on the back (only "B"
    # has 30/04/2010 issue / 07/09/2041 expiry in the sample photo).
    held = ["B"]
    print("Held Lebanese categories:", held)
    print("Mapped IDP boxes to stamp:", categories_to_idp(held))
