"""
Renders the "Cash Receipt" PDF handed to a client after payment — added
2026-09-26 after Georgio shared a video of LAA's own screen, whose
"IDL Applications" tab has "Print Receipt"/"View Receipt" buttons
alongside the existing "Print Licence"/"View Licence" pair this app
already had (see gui/new_idl_form.py's print_to_printer/print_preview).

Unlike printing/print_page.py's booklet-page render (which overlays data
onto a PHYSICAL pre-printed blank page loaded in a dedicated printer
tray — see that module's own docstring), this renders the ENTIRE receipt:
logo, "LEBANON AUTOMOBILE ASSOCIATION" header, "Cash Receipt" title, the
Description/Issued No./Amount table, and the Signature line are all drawn
here, not just the variable data. That's a real difference confirmed
directly from the video (LAA's own "View Receipt" preview shows a
complete, self-contained page, not just data floating over a blank sheet)
and it's simpler for staff too: a receipt prints correctly on any ordinary
printer with plain paper loaded, no special pre-printed stock or tray
needed the way the booklet page requires.

Page size: A4 portrait, the standard default for a plain-paper office
document in Lebanon -- a placeholder in the same sense
printing/layout_config.py's PAGE_SIZE_MM once was before Georgio measured
the real IDP booklet page (see that module's history): correct enough to
build and test against now, but worth confirming once a real printed
receipt can be measured directly.

Logo: see assets/README.md. `_LOGO_PATH` is checked for existence right
before drawing -- the receipt still renders correctly (just without the
logo, text header only) when that file isn't there yet, since Georgio
hadn't sent it as of this feature's initial build. Drop the real file at
that path and every future receipt picks it up automatically, no code
change needed.

"No." (see db/storage.py's next_receipt_number and gui/new_idl_form.py's
_ensure_receipt_number): unlike Issued Document Number, Georgio confirmed
2026-09-26 this should be auto-generated by the app -- LAA's own screen
has no visible field for it at all, it just appears on the printed/
previewed receipt.

Description column: hardcoded to "International Driving Licence" (the
exact wording read off Georgio's video) -- this app only ever produces
International Driving Licences, the same reasoning printing/print_page.py
already documents for hardcoding nationality to "LEBANESE".
"""

from __future__ import annotations

from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle

# See assets/README.md -- checked for existence at render time, not
# assumed to be present.
_LOGO_PATH = Path(__file__).resolve().parent.parent / "assets" / "laa_logo.png"

_ORG_NAME = "LEBANON AUTOMOBILE ASSOCIATION"
_RECEIPT_TITLE = "Cash Receipt"
_DESCRIPTION = "International Driving Licence"

_MARGIN = 20 * mm
_LOGO_SIZE = 20 * mm


def _draw_header(c: canvas.Canvas, page_w: float, top_y: float) -> float:
    """Logo (if present) + org name, side by side. Returns the y position
    (in points, from the page bottom) directly below this block, for the
    caller to continue laying out from."""
    if _LOGO_PATH.exists():
        c.drawImage(
            str(_LOGO_PATH), _MARGIN, top_y - _LOGO_SIZE, width=_LOGO_SIZE, height=_LOGO_SIZE,
            preserveAspectRatio=True, mask="auto",
        )
        text_x = _MARGIN + _LOGO_SIZE + 6 * mm
    else:
        # No logo yet (see assets/README.md) -- the org name still needs
        # to read correctly on its own, so it starts at the left margin
        # instead of leaving an empty gap where the logo would have been.
        text_x = _MARGIN

    c.setFont("Helvetica-Bold", 14)
    c.drawString(text_x, top_y - _LOGO_SIZE / 2 - 3, _ORG_NAME)

    return top_y - _LOGO_SIZE


def _draw_title_and_number(c: canvas.Canvas, page_w: float, y: float, receipt_number: str, date: str) -> float:
    c.setFont("Helvetica-Bold", 13)
    c.drawCentredString(page_w / 2, y, _RECEIPT_TITLE)

    c.setFont("Helvetica", 9)
    c.drawRightString(page_w - _MARGIN, y + 3, f"No.: {receipt_number}")
    c.drawRightString(page_w - _MARGIN, y - 4 * mm + 3, f"Date: {date}")

    return y - 12 * mm


def _draw_received_from(c: canvas.Canvas, y: float, received_from: str) -> float:
    label = "Received from: "
    c.setFont("Helvetica", 10)
    c.drawString(_MARGIN, y, label)
    label_width = c.stringWidth(label, "Helvetica", 10)

    value_x = _MARGIN + label_width
    c.drawString(value_x, y, received_from)
    value_width = c.stringWidth(received_from, "Helvetica", 10)
    # Underline the value only, matching the real receipt (see this
    # module's docstring) rather than underlining the whole line.
    c.line(value_x, y - 2, value_x + max(value_width, 40 * mm), y - 2)

    return y - 10 * mm


def _draw_table(c: canvas.Canvas, page_w: float, y: float, issued_no: str, amount: str) -> float:
    table_width = page_w - 2 * _MARGIN
    col_widths = [table_width * 0.5, table_width * 0.25, table_width * 0.25]
    data = [
        ["Description", "Issued No.", "Amount (LBP)"],
        [_DESCRIPTION, issued_no, amount],
    ]
    table = Table(data, colWidths=col_widths)
    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.75, colors.black),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    table_w, table_h = table.wrapOn(c, table_width, 0)
    table.drawOn(c, _MARGIN, y - table_h)
    return y - table_h


def _draw_signature(c: canvas.Canvas, y: float) -> None:
    c.setFont("Helvetica", 10)
    c.drawString(_MARGIN, y, "Signature:")


def render_receipt(values: dict, output_path: str) -> None:
    """values keys: receipt_number, date, received_from, issued_no,
    amount -- see receipt_values_from_form_fields for how the New IDL
    form's field dict maps onto these."""
    page_w, page_h = A4
    c = canvas.Canvas(output_path, pagesize=A4)

    top_y = page_h - _MARGIN
    y = _draw_header(c, page_w, top_y)
    y -= 10 * mm
    y = _draw_title_and_number(c, page_w, y, values.get("receipt_number", ""), values.get("date", ""))
    y = _draw_received_from(c, y, values.get("received_from", ""))
    y = _draw_table(c, page_w, y, values.get("issued_no", ""), values.get("amount", ""))
    y -= 12 * mm
    _draw_signature(c, y)

    c.showPage()
    c.save()


def receipt_values_from_form_fields(form_fields: dict) -> dict:
    """Maps the New IDL form's field dict to render_receipt's value keys
    -- same v() unwrap-a-FieldRead-or-plain-string helper printing/
    print_page.py's values_from_form_fields already uses, since this gets
    called with both live QLineEdit .text() strings (plain str) and a
    saved IdlRecord's `.fields` values (also plain str, see db/storage.py)."""
    def v(key):
        f = form_fields.get(key)
        return f.value if hasattr(f, "value") else (f or "")

    return {
        "receipt_number": v("Receipt.Number"),
        "date": v("Receipt.Date"),
        "received_from": v("Receipt.Received from"),
        "issued_no": v("Issued Document.Number"),
        "amount": v("Receipt.Amount(LBP)"),
    }


def render_receipt_from_form_fields(field_values: dict, output_path: str) -> None:
    """Shared entry point mirroring printing/print_page.py's
    render_idl_data_page -- callers (gui/new_idl_form.py's view_receipt/
    print_receipt_to_printer) pass the raw form field dict straight
    through rather than pre-mapping it themselves."""
    values = receipt_values_from_form_fields(field_values)
    render_receipt(values, output_path)
